apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-01-01T09:45:52Z"
  generation: 1
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "9121"
  uid: 7f10fd25-a644-4c37-a664-b8bdaee82283
spec:
  containers:
    - image: nginx
      name: nginx
  nodeName: cka-cluster3-worker
